---
- name: Install HTTPD, PHP, mlocate, vim
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - php
        - mlocate
        - vim

