---
- name: Install Packages
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx, Node.js, Git
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - nodejs
        - git

    - name: Download Node.js app from Git
      git:
        repo: https://github.com/fropa/nodejs-hello.git
        dest: /path/to/your/app

    - name: Start Node.js app with PM2
      shell: |
        cd /path/to/your/app
        pm2 start app.js --name "your-app-name"

    - name: Apply roles to the playbook
      hosts: all
      become: yes
      roles:
        - role: nginx_role
        - role: nodejs_role
        - role: git_role

