---
- name: Configure Nginx reverse proxy
  hosts: all
  become: yes
  tasks:
    - name: Copy Nginx configuration file
      copy:
        src: nginx_config.conf
        dest: /etc/nginx/conf.d/your-app.conf
      notify:
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

