---
- name: Install Nginx, Node.js, PM2, Git
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - nodejs
        - pm2
        - git

